name = "bot-worker"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "SUBSCRIBERS"
id = "c1f5a6b255264509ac2ed8f24bf9c511"

# Secrets (set via: wrangler secret put BOT_TOKEN etc):
# BOT_TOKEN
# WEBHOOK_SECRET
