name = "rechitsa-worker"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "rechitsa_storage"
id = "9c419a064d7042d89bd214c99b770383"

[[kv_namespaces]]
binding = "SUBSCRIBERS"
id = "c1f5a6b255264509ac2ed8f24bf9c511"
